export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  EXTENSIONS: "/extensions",
  RING_GROUPS: "/ring-groups",
  QUEUES: "/queues",
  IVR_MENUS: "/ivr-menus",
  CONFERENCES: "/conferences",
  PAGING: "/paging",
  SIP_TRUNKS: "/sip-trunks",
  DIDS: "/dids",
  INBOUND_ROUTES: "/inbound-routes",
  OUTBOUND_ROUTES: "/outbound-routes",
  USERS: "/users",
  CDRS: "/cdrs",
  RECORDINGS: "/recordings",
  VOICEMAIL: "/voicemail",
  AUDIO_PROMPTS: "/audio-prompts",
  TIME_CONDITIONS: "/time-conditions",
  HOLIDAY_CALENDARS: "/holiday-calendars",
  CALLER_ID_RULES: "/caller-id-rules",
  DEVICES: "/devices",
  SMS_CONVERSATIONS: "/sms/conversations",
  SMS_PROVIDERS: "/sms/providers",
  PARKING: "/parking",
  BOSS_ADMIN: "/boss-admin",
  DISPOSITION_CODES: "/disposition-codes",
  AUDIT_LOGS: "/audit-logs",
  TENANT_SETTINGS: "/settings",
  TENANTS: "/tenants",
  ANALYTICS: "/analytics",
  MSP_OVERVIEW: "/msp-overview",
  COMPLIANCE_DNC: "/compliance/dnc-lists",
  COMPLIANCE_CONSENT: "/compliance/consent-records",
  COMPLIANCE_SETTINGS: "/compliance/settings",
  COMPLIANCE_AUDIT: "/compliance/audit-log",
  COMPLIANCE_MONITORING_RULES: "/compliance/monitoring-rules",
  COMPLIANCE_MONITORING_EVALUATIONS: "/compliance/monitoring-evaluations",
  COMPLIANCE_MONITORING_ANALYTICS: "/compliance/monitoring-analytics",
  PROFILE: "/profile",
  SITES: "/sites",
  WFM_SHIFTS: "/wfm/shifts",
  WFM_SCHEDULE: "/wfm/schedule",
  WFM_TIME_OFF: "/wfm/time-off",
  WFM_ANALYTICS: "/wfm/analytics",
  PORT_REQUESTS: "/port-requests",
  MSP_TELEPHONY_PROVIDERS: "/msp/telephony-providers",
} as const

export type Role = "msp_super_admin" | "msp_tech" | "tenant_admin" | "tenant_manager" | "tenant_user"

export const MSP_ROLES: Role[] = ["msp_super_admin", "msp_tech"]

export const PERMISSIONS = {
  MANAGE_PLATFORM: "manage_platform",
  VIEW_ALL_TENANTS: "view_all_tenants",
  MANAGE_TENANT: "manage_tenant",
  VIEW_TENANT: "view_tenant",
  MANAGE_USERS: "manage_users",
  VIEW_USERS: "view_users",
  VIEW_OWN_PROFILE: "view_own_profile",
  EDIT_OWN_PROFILE: "edit_own_profile",
  MANAGE_EXTENSIONS: "manage_extensions",
  VIEW_EXTENSIONS: "view_extensions",
  MANAGE_TRUNKS: "manage_trunks",
  VIEW_TRUNKS: "view_trunks",
  MANAGE_DIDS: "manage_dids",
  VIEW_DIDS: "view_dids",
  MANAGE_INBOUND_ROUTES: "manage_inbound_routes",
  VIEW_INBOUND_ROUTES: "view_inbound_routes",
  MANAGE_OUTBOUND_ROUTES: "manage_outbound_routes",
  VIEW_OUTBOUND_ROUTES: "view_outbound_routes",
  MANAGE_RING_GROUPS: "manage_ring_groups",
  VIEW_RING_GROUPS: "view_ring_groups",
  MANAGE_VOICEMAIL: "manage_voicemail",
  VIEW_VOICEMAIL: "view_voicemail",
  VIEW_CDRS: "view_cdrs",
  MANAGE_RECORDINGS: "manage_recordings",
  VIEW_RECORDINGS: "view_recordings",
  MANAGE_VOICEMAIL_MESSAGES: "manage_voicemail_messages",
  VIEW_VOICEMAIL_MESSAGES: "view_voicemail_messages",
  MANAGE_IVR: "manage_ivr",
  VIEW_IVR: "view_ivr",
  MANAGE_QUEUES: "manage_queues",
  VIEW_QUEUES: "view_queues",
  MANAGE_CONFERENCES: "manage_conferences",
  VIEW_CONFERENCES: "view_conferences",
  MANAGE_PAGING: "manage_paging",
  VIEW_PAGING: "view_paging",
  MANAGE_DEVICES: "manage_devices",
  VIEW_DEVICES: "view_devices",
  MANAGE_SMS: "manage_sms",
  VIEW_SMS: "view_sms",
  VIEW_AUDIT_LOGS: "view_audit_logs",
  MANAGE_COMPLIANCE: "manage_compliance",
  VIEW_COMPLIANCE: "view_compliance",
  MANAGE_WFM: "manage_wfm",
  VIEW_WFM: "view_wfm",
} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]

// Mirrors auth/rbac.py:81-228
export const ROLE_PERMISSIONS: Record<Role, Set<Permission>> = {
  msp_super_admin: new Set(Object.values(PERMISSIONS)),
  msp_tech: new Set(Object.values(PERMISSIONS).filter(p => p !== PERMISSIONS.MANAGE_PLATFORM)),
  tenant_admin: new Set(Object.values(PERMISSIONS).filter(p => p !== PERMISSIONS.MANAGE_PLATFORM && p !== PERMISSIONS.VIEW_ALL_TENANTS)),
  tenant_manager: new Set([
    PERMISSIONS.VIEW_TENANT,
    PERMISSIONS.MANAGE_USERS, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_OWN_PROFILE, PERMISSIONS.EDIT_OWN_PROFILE,
    PERMISSIONS.MANAGE_EXTENSIONS, PERMISSIONS.VIEW_EXTENSIONS,
    PERMISSIONS.VIEW_TRUNKS, PERMISSIONS.VIEW_DIDS,
    PERMISSIONS.VIEW_INBOUND_ROUTES, PERMISSIONS.VIEW_OUTBOUND_ROUTES,
    PERMISSIONS.MANAGE_RING_GROUPS, PERMISSIONS.VIEW_RING_GROUPS,
    PERMISSIONS.MANAGE_VOICEMAIL, PERMISSIONS.VIEW_VOICEMAIL,
    PERMISSIONS.VIEW_CDRS, PERMISSIONS.MANAGE_RECORDINGS, PERMISSIONS.VIEW_RECORDINGS,
    PERMISSIONS.MANAGE_VOICEMAIL_MESSAGES, PERMISSIONS.VIEW_VOICEMAIL_MESSAGES,
    PERMISSIONS.VIEW_IVR, PERMISSIONS.VIEW_QUEUES, PERMISSIONS.VIEW_CONFERENCES, PERMISSIONS.VIEW_PAGING,
    PERMISSIONS.VIEW_DEVICES,
    PERMISSIONS.VIEW_SMS,
    PERMISSIONS.MANAGE_COMPLIANCE, PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.MANAGE_WFM, PERMISSIONS.VIEW_WFM,
  ]),
  tenant_user: new Set([
    PERMISSIONS.VIEW_OWN_PROFILE, PERMISSIONS.EDIT_OWN_PROFILE,
    PERMISSIONS.VIEW_EXTENSIONS, PERMISSIONS.VIEW_RING_GROUPS,
    PERMISSIONS.VIEW_VOICEMAIL, PERMISSIONS.VIEW_CDRS,
    PERMISSIONS.VIEW_RECORDINGS, PERMISSIONS.VIEW_VOICEMAIL_MESSAGES,
    PERMISSIONS.VIEW_SMS,
    PERMISSIONS.VIEW_WFM,
  ]),
}

export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.has(permission) ?? false
}

export function isMspRole(role: Role): boolean {
  return MSP_ROLES.includes(role)
}
