"""Concurrent call simulation load test scenario.

Simulates the API load generated by active phone calls: polling queue
status, checking parking slots, viewing active calls via CDR endpoints,
and accessing queue stats.  This models what the real-time dashboards
and wallboards do during peak call volume.
"""

from __future__ import annotations

import logging
import random
from datetime import datetime, timedelta, timezone

from locust import TaskSet, task

from conftest import API_PREFIX

logger = logging.getLogger(__name__)


class ConcurrentCallsBehavior(TaskSet):
    """Simulated concurrent call load patterns.

    Weighted tasks:
      - simulate_call_start   (weight=3)  — creates CDR record via API
      - check_active_calls    (weight=5)  — polls recent CDRs (active call proxy)
      - check_queue_status    (weight=3)  — polls queue stats
      - check_parking_slots   (weight=2)  — polls parking lot slot states
      - check_agent_status    (weight=2)  — polls agent availability
    """

    def on_start(self) -> None:
        """Ensure we have auth tokens and a tenant ID."""
        self._ensure_auth()
        self._ensure_tenant_id()

    def _ensure_auth(self) -> None:
        if self.user.token_mgr.access_token:
            return
        self.user.do_login()

    def _ensure_tenant_id(self) -> None:
        if self.user.token_mgr.tenant_id:
            return
        self.user.discover_tenant_id()

    @property
    def _headers(self) -> dict[str, str]:
        return self.user.token_mgr.auth_header

    @property
    def _tenant_url(self) -> str:
        tid = self.user.token_mgr.tenant_id
        return f"{API_PREFIX}/tenants/{tid}"

    def _handle_auth_error(self, response) -> bool:
        if response.status_code == 401:
            response.success()
            self.user.do_login()
            return True
        return False

    @task(3)
    def simulate_call_start(self) -> None:
        """Simulate the API load of a new call arriving.

        In reality, CDRs are created by FreeSWITCH via ESL events.
        Here we simulate the read pattern that happens when a call starts:
        the UI immediately queries CDRs and queue stats to reflect
        the new call.
        """
        self._ensure_auth()
        now = datetime.now(timezone.utc)
        date_from = (now - timedelta(seconds=30)).isoformat()

        # Query very recent CDRs — simulates "what just happened"
        with self.client.get(
            f"{self._tenant_url}/cdrs",
            headers=self._headers,
            params={
                "date_from": date_from,
                "date_to": now.isoformat(),
                "limit": 10,
            },
            name="GET /tenants/[id]/cdrs (active calls)",
            catch_response=True,
        ) as resp:
            if resp.status_code == 200:
                resp.success()
            elif not self._handle_auth_error(resp):
                resp.failure(f"simulate_call_start: {resp.status_code}")

    @task(5)
    def check_active_calls(self) -> None:
        """Poll recent CDRs — simulates a wallboard checking active calls.

        Real-time dashboards typically poll CDRs with a tight time window
        to approximate "currently active" calls.
        """
        self._ensure_auth()
        now = datetime.now(timezone.utc)
        date_from = (now - timedelta(minutes=5)).isoformat()

        with self.client.get(
            f"{self._tenant_url}/cdrs",
            headers=self._headers,
            params={
                "date_from": date_from,
                "date_to": now.isoformat(),
                "limit": 100,
            },
            name="GET /tenants/[id]/cdrs (wallboard poll)",
            catch_response=True,
        ) as resp:
            if resp.status_code == 200:
                resp.success()
            elif not self._handle_auth_error(resp):
                resp.failure(f"check_active_calls: {resp.status_code}")

    @task(3)
    def check_queue_status(self) -> None:
        """GET /tenants/{id}/queues/stats — poll all queue stats.

        Wallboards and supervisor dashboards poll this endpoint every
        few seconds during business hours.
        """
        self._ensure_auth()
        with self.client.get(
            f"{self._tenant_url}/queues/stats",
            headers=self._headers,
            name="GET /tenants/[id]/queues/stats",
            catch_response=True,
        ) as resp:
            if resp.status_code == 200:
                resp.success()
            elif not self._handle_auth_error(resp):
                resp.failure(f"check_queue_status: {resp.status_code}")

    @task(2)
    def check_parking_slots(self) -> None:
        """GET /tenants/{id}/parking-lots/slots — poll parking slot states.

        Desk phones and soft clients poll parking status to show which
        slots are occupied.
        """
        self._ensure_auth()
        with self.client.get(
            f"{self._tenant_url}/parking-lots/slots",
            headers=self._headers,
            name="GET /tenants/[id]/parking-lots/slots",
            catch_response=True,
        ) as resp:
            if resp.status_code == 200:
                resp.success()
            elif not self._handle_auth_error(resp):
                resp.failure(f"check_parking_slots: {resp.status_code}")

    @task(2)
    def check_agent_status(self) -> None:
        """GET /tenants/{id}/queues/agent-status — poll agent availability.

        Queue supervisors monitor agent login/logout/break status.
        """
        self._ensure_auth()
        with self.client.get(
            f"{self._tenant_url}/queues/agent-status",
            headers=self._headers,
            name="GET /tenants/[id]/queues/agent-status",
            catch_response=True,
        ) as resp:
            if resp.status_code == 200:
                resp.success()
            elif not self._handle_auth_error(resp):
                resp.failure(f"check_agent_status: {resp.status_code}")
